### ISSUE TITLE
Create custom compile directive for speed gains in custom <option> elements

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#143]
Hello All,

I've been working on Journal Vouchers, which uses `<select>` elements to choose accounts for each row.  These selects have complex options, such as disabled and selected, which slows rendering down.

I've found two ways to improve rendering speed:
 - if an orderBy filter is applied, move the parameter(s) into the controller, rather than declaring it in the view
 - pre-process the array of `<option>`s to add a boolean value ng-disabled can check to reduce on the fly processing

There is currently an open issue in the angularjs git repo https://github.com/angular/angular.js/issues/638 to support `ng-options` with a disabled parameter... but it looks like it may not get included for a while.

We need some directive that ignores data binding, and simply prints a list of options with the correctly disabled and selected elements in the meantime.

**Comment by jniles** [comment]
FYI: Angular now supports both grouping and disabling elements in [ng-options](https://docs.angularjs.org/api/ng/directive/ngOptions).  I am closing this issue, and hope we can update angular soon.

**Comment by DedrickEnc** [comment]
We will work on that, when we will migrate
