### ISSUE TITLE
Posting Inventory donations depends on the group of the inventory

### ISSUE THREAD

**Issue by mbayopanda** [IMA-WorldHealth/bhima#145]
/Stock/Gestion de Stock/Entrer Donation

Disfonctionnement dans le 'Posting Journal" dû au compte de l'inventory
=======================================================
- Affiche une ligne (la ligne du compte de l'inventory mais pas de ligne du compte de classe 7) 

Exemple : 
=======
J'ai remarque que ca depend des produits :
pour la quinine (compte 30011175 - injectable) ca n'affiche qu'une ligne ; mais pour l'aspirine (31111174 - comprime) par exemple ca affiche normalement dans le posting journal.

**Comment by jniles** [comment]
@dedrickenc, is this still an issue?

**Comment by DedrickEnc** [comment]
You can close it
