### ISSUE TITLE
Patient name normalization

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#235]
Various users will enter patient's names in upper case or regular title case (first letter of every word capitalized).    The case of these names should be normalized before storing them in the database.  I propose:

  * Remove/trim any extra whitespace
  * Convert all names into title case before storing in the database

When names are displayed in the client, they can be upper-cased if desired.

We should also create a utility that will scrub the database and fix the previously entered name data.

Question: Where else are names entered (other than patient registration)?  We should normalize those too.

**Comment by jniles** [comment]
Has this been taken competely accounted for?  Or is there some work remaining here?

**Comment by jmcameron** [comment]
The first part is done (normalizing names before saving them to the database).  The second part, making a script that will scrub the old entries in the database, has not been done yet.   I plan to do that after I get the patient edit form working.

**Comment by jmcameron** [comment]
The script has been written and is available in:

    utility/patient/clean_names_db.js

**Comment by jniles** [comment]
Awesome, good to know.
