### ISSUE TITLE
Usability updates for Admin/Accounts page

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#261]
The current Admin / Accounts page shows three columns on the right.  Each one has issues that should be addressed to make it more user-friendly:

**Type** - Currently this shows a type number instead of a readable description.
**Fixed** - Not obvious what this means
**Edit** - These edit links fail with the message "Users are not allowed to edit accounts..." Since noone can edit accounts after they are created, the edit links and this entire column should not be shown.

**Comment by jniles** [comment]
The "edit" report has been reported before (#162).  We should probably fix this sooner rather than later, although our chart of accounts table is undergoing a lot of churn due to reports.

**Comment by jmcameron** [comment]
Completed in pull request https://github.com/IMA-WorldHealth/bhima/pull/298.
