### ISSUE TITLE
Issue with the 'unit' table

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#267]
The 'unit' table has a column 'has_children'.   It seems like this is not necessary since it could be handled by queries?  Steven also noted that even though it seems to be intended as a boolean some rows have odd values for this column.

**Comment by jniles** [comment]
We should confirm that has_children is not used in any algorithms on the server (`controllers/tree.js`) or on the client before taking action.  Would you be willing to investigate this?

**Comment by jmcameron** [comment]
Ok, I'll look at it.

**Comment by jmcameron** [comment]
I grazed through some of the code that uses 'has_children'.   Its use seems legitimate.  Here is a SQL query that could do the same thing:

    SELECT id, name, has_children, unit.id as thisId,
    (SELECT COUNT(*) FROM unit WHERE parent=thisId) AS num_children
    FROM unit

I suppose this is a low-priority item that we can take care of later...

**Comment by jniles** [comment]
Is this on the server or a request from the client?

I agree it's low priority, but be nice to get cleaned up.  I'll leave @DedrickEnc to schedule someone to tackle it when the occassion arises.

**Comment by jmcameron** [comment]
Both. It is in a controller on the server.  On the client it is in directives and partials.   If you prefer, I can take care of this next week.

**Comment by jniles** [comment]
This is fixed in #310.

**Comment by jniles** [comment]
This is fixed in #670.
