### ISSUE TITLE
Design a standard API for plugins

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#307]
We currently have three vastly different plugins for bhima, which are more part of the main application than truly "plugins".  As part of the installation refactor, we should start to think about how a plugin should interact with the application and describe an API to enable the server to:
1. start/stop up the plugin
2. configure the plugin with initial parameters
3. determine if an error has happened in the plugin
4. exchange data with the plugin

If we can nail these details early on, our work with future plugins will be much, much easier.

**Comment by jmcameron** [comment]
I found this article interesting and possibly useful:  
   http://martyalchin.com/2008/jan/10/simple-plugin-framework
The focus here was Django/python.  The first section is generic and applicable.  The rest got a bit more Django specific and less applicable.

**Comment by jmcameron** [comment]
A few other sources that might be worth reviewing:
   http://yuilibrary.com/yui/docs/plugin/
   http://blog.nuclex-games.com/tutorials/cxx/plugin-architecture/

**Comment by jniles** [comment]
That first article is excellent.  Thanks for passing it along!

**Comment by jmcameron** [comment]
There may be a need for another type of plugin:  Site specific functionality.  It seems like some features that we are implemented are definitely generic, but others are Congo-specific (eg, Canevas SNIS).   It seems like it would be useful to allow these non-generic parts to be implemented as some type of plugin (and even possibly be kept in separate git repositories).   But this type of plugin would need the ability to add menu items as well as functionality.

**Comment by jniles** [comment]
This is partially addressed in #554.

**Comment by jniles** [comment]
Thanks to the suggestions by @jmcameron , a plugin manager has landed in bhima (#554) that is extensible and fairly powerful.  I am closing this issue, since it has been directly addressed.  Concerns with the new design should be reported as new issues.
