### ISSUE TITLE
Unable to select all cash accounts in incomes report

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#324]
When you first visit the 'Incomes' report page, items will be listed for either $ or Fc.  Once either currency is selected, you are unable to select both again.    It would be useful to add a 'All' option.   This may possibly be an issue in the Expense report page.

**Comment by jniles** [comment]
I believe this report has changed since the issue was reported, as I cannot reproduce the issue.  The presentation is of cash boxes, without the ability to select currencies.
