### ISSUE TITLE
Error when insert or update currency

### ISSUE THREAD

**Issue by wahono77** [IMA-WorldHealth/bhima#334]
I got error message :
[CONNECT] Internal Server Error
Status Code 500 - "Internal Server Error"
Description
Server returned a '500' internal error response for url '/data/'.
Parameters

thanks

**Comment by jniles** [comment]
Unfortunately, the ability to insert/update currencies is a prototype and was never fully functional.  We expect to remove this configuration page soon, and either 1) find a prepackaged library with a large range of currency support or 2) only allow currency creation during a special installation proceedure.

At this point, angular's [currency filter](https://docs.angularjs.org/api/ng/filter/currency) only supports USD-style currencies.  We have created a mock version to display Congolese francs, but have not expanded any support beyond that.  Do you have any experience in this area or could propose a better solution?

**Comment by wahono77** [comment]
I try debug it and this problem is just about query naming of variable.
separator  and decimal is reserved word in MySQL.

I got in console : 

INSERT INTO currency (name, symbol, separator, decimal) VALUES
('Rupiah', 'Rp', '.', ',');
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual th
at corresponds to your MySQL server version for the right syntax to use near 'se
parator, decimal) VALUES ('Rupiah', 'Rp', '.', ',')' at line 1


I try to run : INSERT INTO currency (name, symbol, separator, decimal) VALUES
('Rupiah', 'Rp', '.', ','); in MySQL directly and got error too.

The solution is add ` sign in field name like this :

INSERT INTO currency (`name`, `symbol`, `separator`, `decimal`) VALUES
('Rupiah', 'Rp', '.', ',');


And separator and decimal didn't mean as reserved word again.

**Comment by wahono77** [comment]
ha ha, I wrote ` before and after field name, but in github this ` sign is invisible

**Comment by wahono77** [comment]
writing aphostrope in github should use "&rsquo;"

**Comment by jniles** [comment]
This is really good analysis, thank you for taking the time to debug it!

 We can schedule a fix in the coming week or so. If you are interested in contributing, or need the feature more urgently, feel free send us a PR.

@jmcameron, would you be willing to sort this out?

**Comment by wahono77** [comment]
Thanks for your offer, I just test this great project. BTW, when beta/RC released?

**Comment by wahono77** [comment]
I don't know what's you mean exactly about "angular's currency filter only supports USD-style currencies". But I try it's OK for all currencies : 

http://jsfiddle.net/wahono77/mds4mpp1/

**Comment by wahono77** [comment]
The simple solution for me is add aphostrope in server/lib/parser.js

exports.insert = function (table, data) {
...
....
  sql = template.replace(/%T%/g, table)
          .replace('%V%', '(`' + values.join('`, `') + '`)')  =======> here is the changes
          .replace('%E%', expressions.join(', '))
          .replace('%project_id%', project_id);
  return sql;

};

**Comment by jmcameron** [comment]
I will be in at the IMA office this afternoon.  I'd be glad to look at this with you then.

**Comment by jniles** [comment]
@wahono77, what I mean by USD style currencies are currencies that have non-comma separators and other types of non-US style currency delimiters.

For example, $1,234.56 is the appropriate value for USD, yet in francs this would be 1 234,56 FC.

I am currently traveling, but will let you know if I get a chance to address this when I next get a chance to code.

**Comment by jmcameron** [comment]
Chris is looking at this right now.  I worked a little with him this afternoon.  In order to fix this insert, I think we will need to update the parser to insert database-specific escaping around every data field name going into the SQL queries.   I've coached all three of them on how to run the mocha tests and made sure that if Chris updates parser.js, he will update the corresponding tests (and thououghly trying the various menu items to make sure nothing breaks).

**Comment by lomamech** [comment]
I try to use the function sanitize() for to solve the problem of mysql keyword for Insert and Update currency but Request sql generad is invalid from the mysql syntax

I also use the solution using the `symbol in the parser.js in case of insertion and updated works well but is not the ideal solution if you change DBMS

I wonder if the right solution would be to not use the keyword Mysql

**Comment by lomamech** [comment]
I have try to check the system white the using of the symbol ` , they are the message error when we use the this link https://localhost:8080/#/permission

**Comment by jniles** [comment]
Do you have a reference branch that I can look at?

**Comment by jmcameron** [comment]
Chris, In your screen dumps, I see that the field names are being quoted with the wrong kinds of qoutes. Apparently we are not doing the right thing to escape the field names.  Maybe Jonathan N can suggest what we should be doing?   Once answer is to always avoid MySQL keywords, but I think that is short-sighted.  I think the better, long-term solution is to properly quote the field names using the low-level functions that are database specific.

**Comment by jniles** [comment]
I have written in a fix that behaves well and test cases for it.

Once again, thank you @wahono77 for bringing this up.  I'm sure keyword issues would have come up sooner or later.  Let us know if there is anything else we can do for you.

**Comment by jniles** [comment]
This fix is now incorporated into the main repository.
