### ISSUE TITLE
Restructure partials directories to be more hierarchical 

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#355]
Restructure some of the partials directories to be hierarchical and functionally grouped.  
For instance, refactor so that

   patient_edit ==> patent/edit
   patient_registration ==> patient/registration
   patient_group_assignment ==> patient/group_assignment
   swap_debtor ==> patient/swap_debtor

In the process, update some names to be a bit more consistent:

   holydays ==> holidays

Please add other refactory/renaming suggestions.

**Comment by jniles** [comment]
@jmcameron , @DedrickEnc , I'll work on this one.

**Comment by DedrickEnc** [comment]
Okay, Jonathan Niles. No ruch take you time to test it.

**Comment by jniles** [comment]
I tested all the modules I changed in #557 .  It requires a database rebuild though, to fix the links found in the `unit` table.

**Comment by jniles** [comment]
Issue resolved in #557.
