### ISSUE TITLE
Financiary Raport : Cash Flow

### ISSUE THREAD

**Issue by DedrickEnc** [IMA-WorldHealth/bhima#39]
I think this is the best time to begin writing some thing for reports : We need the cash flow report.
Please one of us can choose this issue.

**Comment by jniles** [comment]
After some deliberation, Cash Flow is not easy to impliment with Tshikaji's Chart of Accounts.  I would encourage the team to work with the chief accountant to create a cash flow report off of the chart of accounts at Tshikaji, then we will have a better grasp of how to impliment it.

**Comment by jniles** [comment]
@DedrickEnc is this issue still relevant?

**Comment by jniles** [comment]
I believe this issue has been closed.
