### ISSUE TITLE
Posting Journal Server-Side Modularization

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#47]
As we approach the point of re-designing permission and routes, an important redesign goal is should be to modularize the architecture of the server posting journal code.  Current statistics are:

File | Length
------ | ------
`journal.js` | 1825 

The `journal.js` file is already set up for easy modularization.  It exports a central router that calls a given function based on the url parameters.  I propose the following redesign:

__Folder Structure__

```bash
- routes
  - journal
    - core.js         # contains the router export
    - coreutils.js   # contains utility functions common to each route (getTransactionId(), validUser(), ...)
    - engines       # contains the posting logic for each route in an individual file.
        - purchase.js
        - sale.js
        - cash.js
        - caution.js
# ...
```

In this model, `core.js` contains the map from URLs => engine and passes the parameters to each function. Ideally, the code would be incredibly generic and use promises.  An idea looks like this:

```javascript
module.exports = function router (db /*, dependencies */) {
  var utils, map;
  
  utils = require('./coreutils');

  map = {
    'purchase' : require('./engines/purchase')(db, utils),
    'sale' : require('./engines/sale')(db, utils)
    // etc ...
  };

  return function () {
    var args, table;
    args = Array.prototype.slice.call(arguments);
    table = args.unshift();   // get the first argument
    return (!!map[table]) ? map[table](args) : q.reject('No route for table : ' + table);
  };
};
```
This model can then handle any engines added later.  The only change is to add a line into the map.

Each engine then is responsible to doing checks to see if the data is properly set up.  The engine should also contain a rollback function, in case of failure.

Opinions?  Thoughts?

**Comment by jniles** [comment]
This issue now desperately needs to be addressed.  We are currently push ~4.6k lines in the posting journal, some of it duplicated code.

I propose we prioritize this refactor for the coming months while Patrick is cleaning up data.

**Comment by DedrickEnc** [comment]
I finished email report, so I can do it.

**Comment by jniles** [comment]
I've already started, with the #634 branch, if you want to take that over, go ahead.  I'll work on writing protractor tests.
