### ISSUE TITLE
Proposal: Remove the Currency creation page

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#498]
Hi all,

I can no longer see a need for the currency creation page (route `#/currency`).  It seems to me that the currency page will never be used - in fact, the correct design for adding currencies would be incrementally adding currency through patches to the bhima system, and then a selection from a drop down list on installation.

I propose removing this page and any server-side routes that it uses.  What do you guys think?

**Comment by mbayopanda** [comment]
You're not in wrong... Since i began to work with bhima i never use it... I
will talk to Dedrick about it on morning because i think now he's sleeping
:-)

Thanks Jon, nice to see you again among us...

2015-04-28 0:58 GMT+02:00 Jonathan Niles <notifications@github.com>:

**Comment by jniles** [comment]
Sounds good.  It's good to be back. :D

**Comment by DedrickEnc** [comment]
BHIMA must do his best to allow user to work often at high level (not manipulate database directly for example), I was working on how to create a installing procedure, so the user will configure the system through bhima interface during the installation but I stopped for tshikaji trip. We must think about many things such as a new currency must be integrated in the enterprise. If there is no page for currency that will be difficult.

**Comment by jniles** [comment]
I agree with you, but adding/removing currencies is a low-level operation, and we cannot guarantee that a user can perform it safely.  For this reason, I think the supported currencies should only be changed via a system upgrade, the same way that Windows or Linux updates language packs.

I still support removing it.  If a hospital needs a new currency, they should get technical support to upgrade to a new currency layout.  Currencies should not change otherwise, and allowing a user to add currencies is a far greater liability than a benefit.

**Comment by DedrickEnc** [comment]
I agree with you Jon. If you have time you can do it.

**Comment by jniles** [comment]
Okay, will do.

**Comment by jniles** [comment]
Issue resolved in #555.
