### ISSUE TITLE
Hash + salt passwords

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#552]
This is a reminder that we need to implement a scheme for hashing our passwords.   This means that if our database was dumped to the web, the passwords of administrators will not be leaked.

This should be done when authentication is looked at again.

**Comment by DedrickEnc** [comment]
Yes you are right and we have also to make a procedure for helping the user to find his password when lost.

**Comment by jniles** [comment]
I think that a user should be able to change their password (via their email), but I don't think they should be able to see the text of it again.  That is similar to how gmail, Facebook, etc, work.

**Comment by DedrickEnc** [comment]
LGTM

**Comment by jniles** [comment]
Ha!

**Comment by jniles** [comment]
This issue was closed in #611.

**Comment by DedrickEnc** [comment]
According to the discussion that we had about the email purposes for BHIMA, I think we must allow the user retrieving password in BHIMA through the application admin. we don't need to involve email process.

**Comment by jniles** [comment]
Sounds good.
