### ISSUE TITLE
Recursive loop in /#/extra_payment

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#556]
There is an infinite loop generated, locking up the server when using the page `/#/extra_payment`.

Steps to reproduce:
1) sign in
2) access the page `/#/extra_payment` via the tree
3) examine the server console.

**Comment by DedrickEnc** [comment]
ha! you are perspicacious! I just see it

**Comment by DedrickEnc** [comment]
Oh! no Jon, It is not a mistake. data appear little by little. now it stopped

**Comment by jniles** [comment]
[I have never heard that word before](http://dictionary.reference.com/browse/perspicacious).  That's amazing. :D!

It locks up the entire server - if this is expected behavior, it must be changed or opimized.  I fear it will cause problems in production.

**Comment by DedrickEnc** [comment]
We handled a specific situation with that module. When we went to roll out the system, there was some clients who paid their invoices with ProgitSante (ProgitSante does not deal with the patient, it deals only with a global account called IMPAYE, so it is difficult to follow the financial state of a client distinctly).
We recorded January, February and March invoices in BHIMA but It was difficult for us to know if those invoices was paid. The extra ordinary payment is there to be used, when a client has already paid his invoice and BHIMA does not know it.
But you are right, this module was implemented very fast at Tshikaji, it must be cleaned, it is looking for all unpaided sales (that is slowly).

**Comment by jniles** [comment]
Okay, that is understandable.  I might take a look at it, but if it was mostly for migration then we expect it to be used less and less.  Thank you for your quick response.

**Comment by DedrickEnc** [comment]
You're welcome!

**Comment by jniles** [comment]
Can't reproduce in the latest development branch.  Closing this issue.
