### ISSUE TITLE
Exchange rate module does not display date properly

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#588]
Under set today's exchange rate in the exchange rate module, the date is blank in Firefox and 'mm/dd/yyyy' in chrome (with en_US locate).

The module works fine, but it's confusing to not know what date your are adding for.  Furthermore, the lack of appearance in Firefox is a bug.

**Comment by jniles** [comment]
I'll take this one.

**Comment by DedrickEnc** [comment]
Why closing an issue with out solving it?

**Comment by jniles** [comment]
I think the internet messed me up.  It was supposed to only be opened. :S
