### ISSUE TITLE
Switch to using numeral.js in mail plugin locales

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#605]
I didn't realize we depended on [numeral.js](http://numeraljs.com/) for our PDF report currency formats.  The mail plugin currently uses a custom script to do currency formatting - it would be best to depend on numeraljs for the currency conversion if the main bhima application is guaranteed to support it anyway.

**Comment by DedrickEnc** [comment]
I will check if numeraljs can support specific currency such as CDF

**Comment by jniles** [comment]
@DedrickEnc, do you have a progress update on this?

**Comment by DedrickEnc** [comment]
I didn't check it yet.

**Comment by jniles** [comment]
Okay, then I will close this issue and open it in the plugin repository.
