### ISSUE TITLE
Updates for [Stock] Stock Sheet report

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#6149]
Stock > Report > [Stock] Stock Sheet

**Suggestions**
- ~~Fix name:  [Stock] Stock Sheet => Stock Sheet Report~~
- What is the purpose of the "Sort lots movements by their true creation date" option?  Is it necessary?  Does something need fixing to eliminate the need for the option.  (BTW, see Issue https://github.com/IMA-WorldHealth/bhima/issues/6062 and closed PR https://github.com/IMA-WorldHealth/bhima/pull/6094).
- On the resulting report, the legend in the summary line "End value of the stock with the unit cost of the company" should be right justified.  Similarly the legend "Opening Balance" in first row should be right justified.  Also, the term "Stock" in the right most group of columns is ambiguours.  I would suggest something like "Stock Available" or "Stock on hand"  ![image](https://user-images.githubusercontent.com/62145/145442267-36ffc5d5-501f-4d5e-82e2-d56c3818da85.png)

**Comment by jniles** [comment]
I would also switch the client form optional portion around, so the required inventory is above the optional depot.

![image](https://user-images.githubusercontent.com/896472/146011723-ccc16ca2-5c4a-4ae0-8160-3569099cb991.png)

**Comment by jniles** [comment]
> What is the purpose of the "Sort lots movements by their true creation date" option? Is it necessary? Does something need fixing to eliminate the need for the option. (BTW, see Issue Feedback on System Usage Statistics #6062 and closed PR Set created_at dates in BHIMA test data (for System Usage Report) #6094).

Responding specifically to this - it is needed, unfortunately, given that our clients sometimes back-date data.  That makes it hard to make a moving average when the data is out of order - sometimes stock is consumed before it enters or vice versa.  Usually, adding in the created_at date helps make sense of the report so we don't get negative numbers.
