### ISSUE TITLE
Updates for RUMER report

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#6153]
Stock > Report > RUMER

**Suggestions**
- It seems like a more descriptive name would be helpful such as:  Drug Usage Report (RUMER).  In French "Registre d’utilisation des médicaments et recettes (RUMER)"?
- The font sizes for the title block need to be neatened up. 

![image](https://user-images.githubusercontent.com/62145/145465471-acd4677a-8dbd-4ba1-997a-4c9f28c09952.png)

- The English subtitle has the word "Recipes".  This is wrong.  The French subtitle is "**R**egistre d’**u**tilisation des **m**édicaments **e**t **r**ecettes" (which seems to be where RUMER comes from).  This should translate in English to something like:  "Medication Use Records and Receipts" (eg, MURAR!)
- The flag "Exclude inventories without movements and out of stock" does not prevent displaying stock with (erroneous) negative quantities.
- Suggest renaming the flag "Include daily stock balances and out-of-stock percentage" to "Include daily stock balances and out-of-stock percentage details"

**Comment by jniles** [comment]
@jmcameron would you mind tackling this before the close of the release window?

**Comment by jmcameron** [comment]
> @jmcameron would you mind tackling this before the close of the release window?

No problem.
