### ISSUE TITLE
Stock Changes Report is broken

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#6154]
Stock > Report > Stock Changes Report

BUG!   This report crashes for me with the server-side error message: 
- no such file or directory, open  /Bhima/node_modules/chart.js/dist/Chart.min.js'
- In the node_modules directory, the file name is chart.min.js (lower case)
- Fixing this case name in server/controllers/stock/reports/stock_movement_report.handlebars does helps but there is still an error:  TypeError: Cannot read property 'toLowerCase' of undefined

**Comment by jniles** [comment]
It looks like the depot is required and that is the only bug here.
