### ISSUE TITLE
Report generation silently fails 

### ISSUE THREAD

**Issue by sfount** [IMA-WorldHealth/bhima#650]
1. If no valid wkhtmltopdf instance is found on the server BHIMA still responds with URL of the PDF resource that doesn't exist.

2. If no PDF is found, the server crashes and does not report the issue. 

*wkhtmltopdf* should also be a dependency for BHIMA (potentially through bower) however that is a separate architecture issue.

**Comment by sfount** [comment]
Steps for reproducing this issue 
* uninstall wkhtmltopdf (not advised) 
* build a PDF report

**Comment by DedrickEnc** [comment]
(not advised)? Interest.

**Comment by sfount** [comment]
I remember fighting with different wkhtmltopdf versions not working when developing this feature. This would be solved by creating a dependency but I can't guarantee it will be easy to get back after uninstalling!
