### ISSUE TITLE
Confusing Caution UI when no exchange_rate

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#652]
The caution module correctly checks to see if there is an `exchange_rate`; however, it does not report failures to the client.  In particular, the cashbox and currency drop downs do not fill out if there is no currency in place.  Furthermore, you can still search for a patient, but cannot make a caution for them.

The application should alert the user to an error with currencies via a message.  It should also block interaction with the page (like cash does) until the problem is fixed.

**Comment by DedrickEnc** [comment]
Good feedback.

**Comment by jniles** [comment]
This is being addressed in #676.
