### ISSUE TITLE
Use bower for client side dependencies 

### ISSUE THREAD

**Issue by sfount** [IMA-WorldHealth/bhima#660]
We currently do not have a list of client side dependencies required to run BHIMA, instead the current repository has many different 'vendor/lib' files that have been committed as a part of the BHIMA code base. 

I suggest that we use the [bower](http://bower.io/) package manager to store these in exactly the same way we use npm for server side dependencies. 

Our configuration would look something like this 

*bower.json*
```
{ 
  "dependencies" : { 
    "jquery" : "2.1.4",
    "angular" : "x.x..x",
    "angular-translate" : "x.x.x",
    ...
    }
}
```

This would result in an installation process of 
```
npm install 
bower install 
gulp build
```

This would be an opportunity to clearly define development vs. production dependencies and remove code from the BHIMA repository that does not belong to BHIMA. 

I understand that there are pros and cons however. What do you think? If this gets the go ahead I'll go ahead and transition the vendor structure and provide instructions on how to install.

**Comment by jniles** [comment]
I don't see anything wrong with using bower for bhima's dependencies.

There are two considerations:
 1. I remember manually editing angular-ui-bootstraps templates.  Can't remember why, but you might run into errors there ... just a heads up.
 2. I know bower can manage some things like CSS.  Are we just using this for larger libraries (angular-translate, angular, jquery, slick, etc...)?  Or will will we manage bootstrap with bower?

Interested in hearing your feedback,

**Comment by sfount** [comment]
I remember that as well (we had some issues upgrading angular ui to a new version to make use of new features with our older bootstrap styles or something - modifications occured :sweat:), slick grid has some custom CSS too. 

If that is the case we can move any CSS/ JS that has been modified for BHIMA into bhima/client/src/, maybe something like bhima-angular-ui or if we want to over complicate it we could fork the original repositories and then use those as dependencies within BHIMA (probably not worth it).

I would say anything that isn't BHIMA specific becomes a dependency, that includes bootstrap etc. The benefit as far as I can see is that if a new version or dependency needs to included actual files within the repository don't need to be changed - just a line or two of JSON.

**Comment by DedrickEnc** [comment]
I agree, we bower bhima will be more structured. npm for sever side and bower for client side, then gulp to build the entire application. it should be good if we could use one tool for managing the server and the client dependencies but that is okay.

**Comment by sfount** [comment]
Thanks for the feedback Dedrick. It is possible to use npm for client side dependencies however this is not normally done and is not as supported as bower for client libraries in my experience. 

I will look into using npm however I think as the client and server are so seperate having the dependencies seperate wouldn't be a bad thing.

**Comment by jniles** [comment]
I see a lot of value in having two different package managers for client and server.  I often type "npm update" and such to see if there are newer versions of our server modules (with new features) that we can take advantage of.  If that command upgraded the client as well, it would be complete chaos.

**Comment by jniles** [comment]
Closing this as fulfilled in #705.
