### ISSUE TITLE
Change primary cash URL syntax

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#666]
The primary cash stores the cashBoxId parameter in the URL (which is excellent).  However, it could be better structured, inspired by REST conventions.  I propose that we make the cashBoxId follow exactly behind the `/primary_cash` route.  This implies the following adjustments to the URL:

`/primary_cash/transfert/1` --> `/primary_cash/1/transfert`
`/primary_cash/expense/payroll/1` --> `/primary_cash/1/expense/payroll/`
`/primary_cash/expense/cash_return/1` --> `/primary_cash/1/expense/cash_return/`
...etc...

**Comment by DedrickEnc** [comment]
Our way of creating url seems more meaningful, lets keep it. The cashBoxId is the last element you must know and it is logic to put it at the end of a url, and it seems more natural.

**Comment by jniles** [comment]
I disagree that our way of creating the URL is more meaningful. How?  I find the primary_cash URL confusing.   The problem with `primary_cash/payroll/1` is that I think the the ID **1** is associated with the *payroll* module, not the *primary_cash* module.

The HTTP  request  `GET  /primary_cash/transfert/1` makes me think we are getting the first transfer record from the primary cash box; `GET /primary_cash/1/transfert` means we are getting the transfers from the primary cashbox with id 1.

[This article](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api) has a good analysis of API design considerations.

**Comment by jniles** [comment]
With current discussions about deep linking with @sfount, we'll leave this up to a proper design for the primary cash modules.
