### ISSUE TITLE
Set Exchange Rate Console Errors

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#673]
Randomly, setting an exchange rate results in the following console error:
```js
Error: $scope.globalRates is undefined
$scope.submit/<@https://localhost:8080/js/bhima.min.js:3509:1
```

It doesn't seem to happen regularly, and it does not affect the end result (an exchange rate is added), but it should be fixed nonetheless.

**Comment by sfount** [comment]
Along with this I've noticed some pages that use the exchange rate sometimes report it missing from time to time until the page is refreshed or something changes. I haven't investigated this but it may be worth ensuring the design for loading, updating and serving the exchange rate is bullet proof throughout the client.

**Comment by sfount** [comment]
My apologies, it looks like you've reported something like this here #682

**Comment by jniles** [comment]
There are possibly two issues going on here -- first is that we don't get the daily exchange rate on login.  The second is that it might not be correctly recognizing that the daily exchange rate is today's exchange rate.  There's a whole series somewhat-reproducible errors in here that probably means we should re-evaluated the ExchangeService.

**Comment by jniles** [comment]
I'll take this one.
