### ISSUE TITLE
Shouldn't be able to login without permissions

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#681]
You can currently log into bhima even without permissions if your user exists.  This is confusing because the user will not have a tree built (and potentially dangerous since they can still navigate via the URL bar).  We should prevent this by blocking users from logging in if they do not have permissions, potentially with a custom error message.

**Comment by sfount** [comment]
It's a good thing you caught that title. I was about to turn our whitelist into a blacklist :wink:
