### ISSUE TITLE
Consider using period_total table for beginning balances

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#691]
The following PRs migrated us away from using the `period_total`s table: #440, #494 , #516 , #621.

I really, strongly believe that we should reopen the discussion from #274.  Our posting journal + general ledger currently have ~72,500 rows.  Those rows are **only** from 2015-03-31 - 2015-07-10, which is about four months.

We also have 2496 accounts in our chart of accounts.  I know that this number will shrink since we are in the process of migrating from PCGC to OHADA.  However, if every report that needs opening balances and period totals must scan the general_ledger + posting journal, performance is going to decrease *rapidly*.

The right thing to do here, from a developer perspective, is to cache period totals in  the `period_total` table.  We can still bring period totals into our calculations where we need them.

@IMA-WorldHealth/owners I think this discussion needs to had again.  What do you think?

**Comment by sfount** [comment]
From a development perspective I see no problems with using the period_total table. I seem to recall I had initially been hesitant to use this model everywhere as it was a clear point of failure/ (somewhat) duplicated data however I completely agree with your analysis. 

72,500 rows is a lot to process on its own, not even considering that we use extremely expensive UUIDs that require costly joins for more complicated calculations.

(You can @IMA-WorldHealth/owners ?! Cool)

**Comment by DedrickEnc** [comment]
Let talk about that when every body will be in Kinshasa, thank you Jon to open this issue.

**Comment by jniles** [comment]
This discussion has finally come to a close.  Beginning balances are implemented as a single transaction in the posting journal and are therefore reflected in the `period_total` table.
