### ISSUE TITLE
Stock Status report sends too many HTTP requests

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#698]
The stock status report (`/reports/stock_status/`) sends too many HTTP requests.  It suffers from the same design flaws as #624 and #679.  To see this, try the following:
```sh
# pipe output of command to logfile
$ npm run app > out.log
# login into bhima and count number of lines in log
$ wc -l out.log
130 out.log
# navigate to the reports/stock_status page
$ wc -l out.log
1618 out.log
```
That's ~1,300 requests for what probably should have been at most 3 requests.  On Chrome (Version 45.0.2454.85 (64-bit)) running on Linux Mint, this page crashes the browser.

These types of design mistakes seem to be common throughout bhima.  @DedrickEnc, we should schedule a code audit and make sure we fix all of these design flaws before the next release cycle.

**Comment by DedrickEnc** [comment]
Got it
