### ISSUE TITLE
Use ng-options for <select> elements

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#701]
In quite a few places, we have code that looks like this:
```html
<select>
  <option ng-repeat="i in list" ng-value="" ng-selected="">{{ i }}</option>
</select>
```

[Here](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/partials/inventory/groups/groups.html#L101) [are](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/partials/reports_proposed/grand_livre/grand_livre.html#L31) [some](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/partials/creditor/group/creditor_group.html#L74) [places](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/partials/debtor/debtor_group.html#L94) [where]() [this pattern](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/partials/reports/operating_account/operating_account.html#L18) [is used](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/partials/reference/reference.html#L106).

Using `ng-repeat` on the `<select>` makes the ng-model bind a string, which requires extra work on the programmer's part to figure out what the model was actually supposed to be bound to.

We should really try to avoid using this pattern in the future.  As part of our refactor towards the end of the year, we should ensure that all these elements are changed out for `ng-option`s.

[According to the angular documentation](https://docs.angularjs.org/api/ng/directive/select):

> In many cases, ngRepeat can be used on <option> elements instead of ngOptions to achieve a similar result.  However, ngOptions provides some benefits, such as more flexibility in how the <select>'s model is assigned via the select as part of the comprehension expression, and additionally in reducing memory and increasing speed by not creating a new scope for each repeated instance.

**Comment by sfount** [comment]
This is an excellent suggestion for general practice and I agree we should go back and improve this pattern where possible. (In practice ng-options is __significantly__ faster).

However in some cases ng-options does not provide the functionality required. It is impossible to disable individual option elements on a select using this directive. Sometimes it useful to demonstrate to a user that an option is available but cannot be selected/ is disabled. This pattern is also used to title selects in a number of places. 

#700 is a good example of ng-options not providing the required functionality.

**Comment by sfount** [comment]
My previous comment can be ignored as of #706

**Comment by jniles** [comment]
The merits of this have been proved on many pages, even with complex disabled options and hierarchies.  The most complex case can be seen [here](https://github.com/IMA-WorldHealth/bhima/blob/development/client/src/partials/cash/cashboxes/modal.html#L24).
