### ISSUE TITLE
Journal date filter does not match dates correctly

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#713]
The SlickGrid date filter we are using does not match days correctly.  When filtering for a given date (say 2015-09-23), the filter does not match the last number, resulting in no values in the view.  To see values, you must use the day before.

This should be an easy fix.

**Comment by DedrickEnc** [comment]
It is adding one day right? when you tape 2015-05-13 you will see records of 2015-05-14.

**Comment by jniles** [comment]
@DedrickEnc , yes that is correct.
