### ISSUE TITLE
Standardize, categorize, and remove uncategorized.js

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#717]
We still have a lot of application logic wrapped up in `uncategorized.js`.  Similar to the gigantic `journal.js` refactor (#634) that was just undertaken, we need to refactor `uncategorized.js` and put routes into logical controllers with logical URLs.

I also assume some of the routes are dead, and do not have any requests sent to them.  We could remove these.  Finally, all routes should conform to jshint standards and use correct `db.exec()` parameter passing.

I am marking this as high priority because I'd like to see it done before the next Tshikaji trip.  It is vital to the maintainability of the system.  If nobody else wants to work on it, I can spend a week or so working out the kinks.

**Comment by sfount** [comment]
I agree that this is a high priority task. 

My main concern is that it would be extremely difficult to fully test every single route updated in this project. The only viable option I can think of is to make the structural change and then respond to the (hopefully very few) errors that occur from it. This would involve having a very thorough review of the application before the next Tshikaji update. 

I would @jniles continues with other projects on your TODO list as you have recently spent a good deal of time refactoring journal #634.

If this project remains open I'm able to start on it in the next few days.

**Comment by jniles** [comment]
Just a heads up, I'm working on refactoring the Stock Dashboard `#/stock_dashboard/`, which involves ~12 or so of these routes.  If anyone is going to start working on `uncategorised.js` make sure they coordinate with me so that we don't end up with massive clashes.

**Comment by sfount** [comment]
From my end it looks like no one has picked this up yet. If nothing else comes up I will begin working on it  shortly.

**Comment by jniles** [comment]
@sfount, I am currently working on stock dashboard which touches a few of these routes.  I plan to be done in ~2 days.  The routes I'm using I moved into `server/controllers/stock.js`.  If it works for you, I could push my work to an IMA branch, and then you could pull and start on uncategorized from there.  I won't be using any of the routes in it that I've left behind.

**Comment by sfount** [comment]
I won't be starting this immediately tomorrow so it shouldn't be an issue, I'll keep in mind that stock has been addressed and work with you sooner the time to pull in your changes before creating multiple redundant routes.

**Comment by jniles** [comment]
Okay, that sounds like a good plan.

**Comment by jniles** [comment]
This has landed in development.
