### ISSUE TITLE
Adopt 'Controller As' Syntax and Deprecate $scope

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#719]
I"m putting this one up for discussion and visibility.  In my opinion, this is the way forward.

Angular gives us the 'Controller As' syntax to bind a controller directly to the DOM.  It looks like this:
```js
angular.module('ExampleApp', []);

function routeConfig($routeProvider) {
  $routeProvider.when('/', {
    controller : 'ExampleController as ExampleCtrl',
    templateUrl : 'example.html'
  });
}

angular.config(['$routeProvider', routeConfig]);
```

It is currently used in [login.js](https://github.com/IMA-WorldHealth/bhima/blob/development/client/src/partials/auth/login.js) and [login.html](https://github.com/IMA-WorldHealth/bhima/blob/development/client/src/partials/auth/login.html), if you would like to see it in a live application.  You can either explicitly use ` { controller : 'Controller as Alias' }` or use `{ controller : 'Controller', controllerAs : 'Alias' }`.

What this does is bind the controller to the DOM, so that you can use the `this` keyword in place of $scope.  This commonly looks like this:

```js
angular.module('ExampleApp')
.controller('ExampleController', ExampleController);

function ExampleController() {
  var vm = this;  // vm stand for view-model
  vm.hello = 'world!'
}
```
... and in the DOM...
```html
<!-- example.html -->
<section>{{ ExampleCtrl.hello }}</section>
<!-- this will render to <section>world!</section> -->
```

Why abandon $scope?  To me, $scope is an unclear dependency on Angular.  It is verbose, and difficult to type (that $).  If our purpose is to write clean code, $scope is not helping us.  Additionally, we have all used `$scope.session` or `$scope.params` or `$scope.data` or `$scope.models` to try and get around the issue of not having a dot (object.property) in the view.  By binding to the controller, we always have the top-level controller alias in the reference `{{ alias.property }}`.

Nested $scopes are also clearer to debug in the HTML.  For example,
```html
<section>
   <h3> {{ parent.property }} </h3>
   <div ng-controller="ChildController as child">
     {{ child.property }}
   </div>
</section>
```
The code is self-describing.  We have these relationships in our index.html file, and some of the files that load other templates via `ng-include`.

Finally, since we are beginning to think about testability and long term maintenance, attaching properties and methods to the controller is *much* easier to test than injecting $scope.  You can simply call `new Controller()` and verify that the correct properties are loaded rather than creating a new $scope (using `$rootScope.new()`) and injecting it into the controller.

There are a few cases where you need $scope, and it should be used.  Cases like using event emitters ($scope.$on, $scope.$broadcast, etc) and when you need access to a form controller on the $scope, but these instances have been rare in our application, and probably need to be refactored (they are hard to test).  Feel free to use $scope if you need it, but question strongly whether you actually need it or not.

It it my opinion going forward that all new code should start without requiring $scope.  What do the maintainers think?  @IMA-WorldHealth/owners ?

**Comment by sfount** [comment]
@jniles In my opinion this is an excellent suggestion. From a clarity/ readability perspective as well as for testing, you have very clearly explained the benefits. 

To add to this, this structure would enable us to use this syntax
```javascript
angular.module('ExampleApp').controller('ExampleController', ExampleController);

ExampleController.$inject = ['ServiceDependency'];

function ExampleController(ServiceDependency) { 
  //...
}
```

In my opinion this is also _much_ clearer than our current layout 
```javascript
angular.module('ExampleApp')
.controller('ExampleController', ['ServiceDependency', ExampleController]);

function ExampleController(ServiceDependency) { 
  //...
}
```

To anyone unfamiliar with angular syntax the second (current) version does not make any sense, why would you bundle any number of strings followed by a function? 

The reason we *cannot* just allow angular to find dependencies on its own (without using any form of $inject) is the code could then not be minified as this would obfuscate the dependency variable names. 

The proposed layout keeps the use of string literals using the $inject variable, whilst this is not standard JavaScript it clearly labels that the following will be injected or passed into the method it is attached to. 

I don't think we'll gain or lose too much either way, I'd be interested to hear if you think this looks cleaner and more semantic or not. @IMA-WorldHealth/owners.

**Comment by jniles** [comment]
I'm okay with the `$inject` syntax.  It's always felt weird to me, but I do agree that it cleans the code up and is more logical than an array of strings, terminated by a function.

I think it is important though, as you have done in your example, the make sure the `Controller.$inject = []` definition is located at the top of your code *near the angular.controller definition*.  This will make sure that we always know where to look to see that the parameters are passed correctly.

**Comment by DedrickEnc** [comment]
Yes @sfount, the **controller.$inject** syntax is very expressive and semantic, even a novice can read the code and understand it. I agree also about aliasing, that will help us a lot even in term of RAM memory because we will not be supposed to load the big object $scope but we still be able to load it if necessary.
Using the **AS** operator when declaring a controller is very optimal because ***it let you have only what you need***.
I will begin by changing some controllers, if there is not **problem**.

**Comment by jniles** [comment]
Thank you all for the excellent discussion.  I will close this issue with the understanding that, going forward, all controllers should be formatted using 'Controller As' and 'Controller.$inject' syntax.  Any PR that creates a new controller should use this syntax before it is merged.
