### ISSUE TITLE
Confirm Purchase Orders is Broken

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#740]
When trying to confirm a purchase order, the server breaks with an MySQL error:
```sh
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1
```

Expected Result: Purchase order confirmed, possibly a receipt
Actual Result: Server breaks, goes into undefined states, sometimes client refuses to reconnect.

**Comment by DedrickEnc** [comment]
Thank you for the feedback.
