### ISSUE TITLE
Stock Distribution Possibly Broken

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#741]
The stock distribution doesn't seem to find patient sale records, for all patients and products tried so far.

Here are some example sales:
![sale1](https://cloud.githubusercontent.com/assets/896472/9874579/cacf77b2-5b9e-11e5-81a2-c90d5a43bd37.png)
![sale2](https://cloud.githubusercontent.com/assets/896472/9874582/cc5cfd0c-5b9e-11e5-8599-637066deecfd.png)

Both these sales result in a "No sale found" message.

Expected Result:  The pharmacy finds a patient sale, and begins distributing stock to them.
Actual Result: "No sales found" message, and unclear how to proceed.

**Comment by DedrickEnc** [comment]
This error, is in the chris found errors list, it will be corrected.

**Comment by jniles** [comment]
This is reported fixed in #843.
