### ISSUE TITLE
Proposal: rework server configuration into fewer, top-level files

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#753]
Currently, bhima uses a whole directory `server/config/` to configure and run the server.  Many of these files are small and contain ~~bad ideas~~ outdated configuration parameters.  It looks like this:
```
server/
    app.js
    config/
         express.js
         routes.js
     environment/
         errors.json
         server.js
     keys/
         # tls keys
```

Here is my new proposal:
```
config.js         # config.js replaces server.js
server/
   app.js          # app.js absorbs express.js
   controllers/
        index.js  # index.js replaces routes.js
```
... and we completely delete errors.json.  It was a *Bad Idea (tm)* (I can say that, since I wrote it).

Currently, app.js loads `config/express.js` which configures loggers, authentication, the database, and sessions, and more.  I see no advantage to doing this in a separate file.  We should put those configurations directly in the app.js file.

Furthermore, I think we are migrating all of our routes into controllers/ or lib/ functions.  To reinforce that our routes belong in controllers, we can create a `controllers/index.js`, which does the same thing as routes.js currently does.  Using the name index.js is appropriate for nodejs, since it means that app.js only needs to do `require('./controllers')(app, cfg)` to load the file.

I think that should cover the majority of cases.  Most projects keep their configuration in one place, at the top level in config.js[on].  This proposal will make building and testing much easier.

There is still a question of what to do with TLS keys.  I would put them in the top level here, but I am not sure of a better solution.  We could research that in conjunction with #707.

What do you all think @IMA-WorldHealth/owners ?

**Comment by sfount** [comment]
Hi @jniles. All of the issues from the last few days are just coming through for me, I'm on a train so I'll just leave very quick initial thoughts and come back and clean this up with a good connection.

* the reason for the environment folder was actually to do with your proposal in #752. It was originally not intended to be anything to do with 'errors' or 'server' but allow us to define a core config that would then be extended (combined) with a development.js or production.js or testing.js depending on something like NODE_ENV. I'm not sure I'd call this a 'bad idea' but it was never fully realised. Bringing this up in both of these issues should cover how we should progress on that.
* no big issues about doing all express configuration in app.js however it is configuration and if properly documented would allow very clear explanation of I smaller components. there is actually quite a lot of non obvious code in this file that would be scattered around the application vs. 'This sets up and configures the HTTP server, this sets up the routes, this sets up the plugins' etc. I don't feel very strongly on this one and it should be fine either way
* I personally think the index idea is pretty cool however we should think about if it makes things more abstract to web developers. Matching /routes/ to controllers and /server side routing/ are very common ideas in almost all web frameworks. Calling this concept a controller index would be quite specific to our project. 

Now that we're able to focus on building, testing and refining the code base we have a very clear goal for how the repository should be layed out, I think this is an important issue to tackle. 

Hopefully this will provide some background/ thoughts on some of your points. Will follow up with revisions and clearer thoughts shortly as mentioned.

**Comment by jniles** [comment]
@sfount, thanks for the feedback.

What would have been contained in the environment folder?  It seems more appropriate for a single configuration file than a folder, although I can see something like `development.js`, `production.js`, etc.  That would work as well, but we still need a master switch somewhere.  I'm not religiously opposed to simply passing the parameter in using a call to node `node ENV=production server/app.js` but this may be unclear and further limit us when we try to make our code run on Travis, etc.

RE: configuration, a linear progression through app.js makes the most sense to me.  We do not have so much configuration code that it will be untenable.  It is difficult currently to know where certain configuration parameters are kept without opening ~three files to check if they are defined there.

I originally typed up both #752 and this in the same proposal, but separated them because I felt like they could be done separately.  Maybe they are inter-related.  Consider them both part of the same proposal.

**Comment by jniles** [comment]
A variant of our discussion has landed in `development`.  Any corrections should be handled in a separate issue.
