### ISSUE TITLE
Pass report parameters through URL querystring

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#797]
For HTML-based reports, sometimes we might want to link to specific report views from outside of the reports module.  Our current practice is to direct the user to a configuration page, allow them to select parameters, submit and create the report.

In order to allow linking from other modules, I propose that the reports also parse the query string passed to them and potentially skip the configuration step if they have enough information to build a report.  For example, seeing all expirations for a given depot might be `/reports/expirations?depots={depotId}&start=01-01-2001&end=12-12-2030`, which would skip the configuration step and directly display the report filtered on `{depotId}` between start and end dates.

#####  Why?
This proposal allows us to "deep link" reports, extending their power by allowing us to link the view they provide from other modules.  Here is a real example that can be improved by linking: in the stock dashboard, there are routes [/reports/expiring/expired](https://github.com/IMA-WorldHealth/bhima/blob/development/client/src/partials/stock_dashboard/stock_dashboard.html#L158), [/reports/expiring/expired30](https://github.com/IMA-WorldHealth/bhima/blob/development/client/src/partials/stock_dashboard/stock_dashboard.html#L165), [/reports/expiring/expired90](https://github.com/IMA-WorldHealth/bhima/blob/development/client/src/partials/stock_dashboard/stock_dashboard.html#L172), and so on.

If this was well designed, a single controller and html page was behind these links; in a poorly designed system, this might result in duplicated logic in identical controllers.  Even in a well designed system, there would needed to be either four new routes in the application router, or a regular expression, and then manual parsing of the URL within the controller.  *We can do better*.

This proposal would allow the author to simply write something like: `ng-href="#/reports/expiring?start={{report.start}}&end={{report.end}}"`.  If they felt that they needed a new timeframe (say, expiring in one week), *they only need to change a single file*, the one linking to the report.

An alternative method to achieve these links is by using a generic ReportParameterService.  This works, but it is more confusing in my view.  However, I'm willing to entertain proposals about a service architecture to solve this problem.

@IMA-WorldHealth/owners thoughts?

**Comment by DedrickEnc** [comment]
Yes, we can do better for report.
Is there a way to use the POST and the GET method in our report module?
So the configuration form  will begin testing if all required parameter are configured and then send the GET request or POST request if needed parameters are not configured.

**Comment by jniles** [comment]
I'm not sure I understand your question.  You can always send a GET/POST using `$http`.  The difference would be, instead of waiting for the user to specify parameters, you can do something like 

```js
var query = $location.search();
vm.start = query.start || new Date();  // default to today
vm.end = query.end || new Date();  // default to today
vm.depot  = query.depot; // defaults undefined, first <option> in the <select>

if (valid(query)) {               // check if all required parameters exist
  vm.search();                   // fire of the report request, using the start, end, depot params.
}
```

**Comment by jniles** [comment]
@DedrickEnc, what report module?  I wasn't aware that we had a generic report module.

**Comment by DedrickEnc** [comment]
Yes, got it.
We will keep the configuration form and show it if necessary.

**Comment by jniles** [comment]
Okay, sounds good.  Closing this as it has been resolved.
