### ISSUE TITLE
Journal Voucher : No total when reloading the form

### ISSUE THREAD

**Issue by DedrickEnc** [IMA-WorldHealth/bhima#816]
When reloading the page to continue the transcation adding process, there is no value for total.
**Step to bug** 
1. Go to journal voucher
2. make a transaction
3. Before validate leave the page and go somewhere else
4. Return to the journal voucher page
5. Click the button to reload the previous form.

**Notice**
 No value for the sum.

**Comment by jniles** [comment]
This is fixed in #817

**Comment by jniles** [comment]
This issue probably shouldn't have been closed until the PR is merged...

**Comment by jniles** [comment]
Merged.
