### ISSUE TITLE
Fiscal Year Module does not correctly handle errors

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#823]
The fiscal year module does not seem to report errors to the client properly.

**(Rough) steps to reproduce**
 1. Run the following code to rebuild a fresh db build, and delete all fiscal year information.
  ```sh
#!/bin/bash
read -p "Enter your mysql user (default root): " user
user=${user:-root}

echo -n "Enter password: " 
read -s pw
echo

# rebuild database
mysql -u $user -p$pw bhima < server/models/development/bhima_structure.sql
mysql -u $user -p$pw bhima < server/models/development/bhima_data.sql
mysql -u $user -p$pw bhima < server/models/development/update/synt.sql

echo "deleting data for tests"
mysql -u $user -p$pw bhima -e "delete from posting_journal;"
mysql -u $user -p$pw bhima -e "delete from general_ledger;;"
mysql -u $user -p$pw bhima -e "delete from period_total;"
mysql -u $user -p$pw bhima -e "delete from period;"
mysql -u $user -p$pw bhima -e "delete from fiscal_year;"
```
 2. Create a new fiscal year, with no opening balances.
 3. Create a second fiscal year, closing the first.
 3. Observe this server console error: 

 ```sh
Error: No period or fiscal year data for date: 2015-10-20
```
 4. Create a third fiscal year, closing the second. 
 5. Observe this server console error:

 ```sh
TypeError: Cannot read property 'map' of undefined
at postingResultat # etc...
```
 6. Note that none of these errors are visible to the user, but are available in the console.

**Expected Results**
 1. There should be no errors.
 2. When there are errors, they should be clearly shown on the client.

This is related to #772, but provides more accurate steps to reproduce.

**Comment by mbayopanda** [comment]
J'ai reconstruit la base de données et nettoyé certaines table comme suit :
```sql 
TRUNCATE `general_ledger`;
TRUNCATE `posting_journal`;
DELETE FROM `period_total`;
DELETE FROM `period`;
DELETE FROM `fiscal_year`; 
```

Puis; j'ai créer une nouvelle année fiscale (Exemple: IMCK 2015) sans balance d'ouverture

Puis; j'ai créer une nouvelle année fiscale (Exemple: IMCK 2016) avec l'option fermer l'année fiscale précédente (IMCK 2015), et je n'ai point observer d'erreur ni du  coté client, ni du coté serveur.

Et finalement; j'ai créer une nouvelle année fiscale (Exemple: IMCK 2017) avec l'option fermer l'année fiscale précédente (IMCK 2016), et je n'ai toujours point trouver d'erreur ni du coté client, ni du coté serveur.
