### ISSUE TITLE
We need the way to repost a transaction

### ISSUE THREAD

**Issue by DedrickEnc** [IMA-WorldHealth/bhima#835]
Some transaction contain good date which belong to the bad period or fiscal year.
The solution is to re-post them, that will allow the system to recalculate some information such as period and the fiscal year.

**Comment by jniles** [comment]
:+1:  Sounds like this should be part of the posting journal.

**Comment by DedrickEnc** [comment]
of course

**Comment by jniles** [comment]
Closed in #841.
