### ISSUE TITLE
Stock Dashboard doesn't need integrated stock in purchase zone

### ISSUE THREAD

**Issue by mbayopanda** [IMA-WorldHealth/bhima#911]
Dans le Tableau de bord du stock, nous ne devons pas avoir les stocks integrEs via le module `stock integration`, en d'autre mots : les purchases avec is_integration = 1 dans la zone `purchase`

![stock dash is_integration](https://cloud.githubusercontent.com/assets/5445251/10992264/a5c73a42-8464-11e5-91db-78e4f10f2977.png)

**Comment by jniles** [comment]
@mbayopanda, is this still an issue? If not, you should implement a fix for it.

**Comment by mbayopanda** [comment]
I have fixed it already...  Thanks

**Comment by jniles** [comment]
In the future, if you can close issues when you complete them?  You can do it via a git commit: just type "Closes #XX" or "Fixes #YYY"  or go to github and close the issue from the web interface.
